[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "raft"
version = "0.0.1"
description = "A relatively small toolbox for processing data ACFR AUV data"
authors = ["Martin Kvisvik Larsen <martin.kvisvik.larsen@hotmail.com>"]
readme = "README.md"
packages = [{include = "raft", from="src"}]
package-mode = true

[tool.poetry.dependencies]
python = "^3.12"
arrow = "^1.3.0"
h5py = "^3.11.0"
loguru = "^0.7.2"
numpy = "^1.26.4"
polars = "^0.20.26"
python-dotenv = "^1.0.1"
python-rclone = "*"
result = "^0.16.1"
toml = "^0.10.2"
tqdm = "^4.66.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
black = {extras = ["jupyter"], version = "^24.4.2"}
jupyter = "^1.0.0"
geoplot = "^0.5.1"

[tool.poetry.scripts]
raft-cli = "raft.cli:main"
