[binaries]
search = "binaries"         # key to look for in the search file
destination = "bin"         # destination directory search result

[usbl]
search = "usbl"
destination = "usbl"

[messages]
search = "messages"
destination = "messages"
