[afft.tasks.build_deployment_bundle.message_map]

VIS = "ImageCaptureMessageV1"
SEABIRD = "SeabirdCTDMessageV1"
AANDERAA_4319 = "AanderaaCTDMessageV1"
ECOPUCK = "EcopuckMessageV1"
PAROSCI = "ParosciPressureMessageV1"
RDI = "TeledyneDVLMessageV1"
LQMODEM = "TrackLinkModemMessageV1"
EVOLOGICS_FIX = "EvologicsModemMessageV1"
BATT = "BatteryMessageV1"
BATT0 = "BatteryMessageV1"
BATT1 = "BatteryMessageV1"
BATT2 = "BatteryMessageV1"
THR_PORT = "ThrusterMessageV1"
THR_STBD = "ThrusterMessageV1"
THR_VERT = "ThrusterMessageV1"
OAS = "OASonarMessageV1"
MICRON = "MicronSonarMessageV1"
MICRON_RETURNS = "MicronSonarMessageV1"
GPS_GSV = "GpsGsvMessageV1"
GPS_RMC = "GpsRmcMessageV1"
