[message_maps]

VIS = "ImageCaptureMessage"
SEABIRD = "SeabirdCTDMessage"
AANDERAA = "AanderaaCTDMessage"
ECOPUCK = "EcopuckMessage"
PAROSCI = "ParosciPressureMessage"
RDI = "TeledyneDVLMessage"
LQMODEM = "TrackLinkModemMessage"
EVOLOGICS_FIX = "EvologicsModemMessage"
BATT = "BatteryMessage"
BATT0 = "BatteryMessage"
BATT1 = "BatteryMessage"
BATT2 = "BatteryMessage"
THR_PORT = "ThrusterMessage"
THR_STBD = "ThrusterMessage"
THR_VERT = "ThrusterMessage"
OAS = "OASonarMessage"
MICRON = "MicronSonarMessage"
MICRON_RETURNS = "MicronSonarMessage"

# NOTE: Currently unimplemented messages
# GPS_GSV = ""
# GPS_RMC = ""
# MICRON_TRACE = ""
# MICRON_SECTOR = ""


[table_names]

VIS = "image_capture"
SEABIRD = "ctd_seabird"
AANDERAA = "ctd_aanderaa"
ECOPUCK = "water_ecopuck"
PAROSCI = "pressure_parosci"
RDI = "dvl_teledyne"
LQMODEM = "modem_track_link"
EVOLOGICS_FIX = "modem_evologics"
BATT = "batteries"
BATT0 = "batteries"
BATT1 = "batteries"
BATT2 = "batteries"
THR_PORT = "thrusters"
THR_STBD = "thrusters"
THR_VERT = "thrusters"
OAS = "sonar_obstacle_avoidance"
MICRON = "sonar_micron"
MICRON_RETURNS = "sonar_micron_returns"
