name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install --user poetry
    - name: Install packages
      run: |
        poetry install
    - name: Build project
      run: |
        poetry build
    - name: Run CLI
      run: |
        poetry run afft --help
    - name: Run tests
      run: |
        poetry run pytest
